/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_radiance_scala_tonclient_TonContextScala */

#ifndef _Included_com_radiance_scala_tonclient_TonContextScala
#define _Included_com_radiance_scala_tonclient_TonContextScala
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_radiance_scala_tonclient_TonContextScala
 * Method:     createContext
 * Signature:  (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_scala_tonclient_TonContextScala_createContext
        (JNIEnv*, jobject, jstring);

/*
 * Class:      com_radiance_scala_tonclient_TonContextScala
 * Method:     destroyContext
 * Signature:  (I)V
 */
JNIEXPORT void JNICALL Java_com_radiance_scala_tonclient_TonContextScala_destroyContext
(JNIEnv*, jobject, jint);

/*
 * Class:      com_radiance_scala_tonclient_TonContextScala
 * Method:     asyncRequest
 * Signature:  (ILjava/lang/String;Ljava/lang/String;Lscala/concurrent/Promise;)V
 */
JNIEXPORT void JNICALL Java_com_radiance_scala_tonclient_TonContextScala_asyncRequest
(JNIEnv*, jobject, jint, jstring, jstring, jobject);

/*
 * Class:      com_radiance_scala_tonclient_TonContextScala
 * Method:     syncRequest
 * Signature:  (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_radiance_scala_tonclient_TonContextScala_syncRequest
        (JNIEnv*, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif